name: Build LaTeX diff document
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      PAPER: "main"
      MAIN: ${{ github.event.pull_request.base.sha }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compile LaTeX diff
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            ${{ env.PAPER }}-diff${{ env.MAIN }}.tex
          working_directory: "tex"
          extra_system_packages: "git patch"
          latexmk_shell_escape: true
          pre_compile: git config --global --add safe.directory /github/workspace && latexdiff-vc --git --flatten --disable-auto-mbox --append-safecmd="MINARES" --exclude-safecmd="Cref,Cref\*,hspace" -r ${{ env.MAIN }} ${{ env.PAPER }}.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: DiffPDF
          path: |
            tex/${{ env.PAPER }}-diff${{ env.MAIN }}.pdf
